# Generated by Django 5.1 on 2024-08-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_inmueble',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_inmueble', models.CharField(choices=[('CS', 'Casa'), ('APTO', 'Apartamento'), ('APTOES', 'Aparta Estudio')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='inmueble',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=25)),
                ('costo', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('DISP', 'Diponible'), ('VEND', 'Vendido'), ('ARR', 'Arrendado')], max_length=15)),
                ('id_tipo_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inmuebles.tipo_inmueble')),
            ],
        ),
    ]
