# Generated by Django 5.1 on 2024-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_inmueble',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_inmueble', models.CharField(choices=[('CS', 'Casa'), ('APTO', 'Apartamento'), ('APTOES', 'Aparta Estudio')], max_length=25)),
            ],
        ),
    ]
